name: DEPLOY TO DEDICATED SERVER
on:
  push:
    branches:
    - master
    - CI
    - CD
    - CICD
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete --exclude="" --include="" --filter=""
        path: .
        remote_path: ~/ebird/server
        remote_host: www.wyvernpserver.tech
        remote_port: 22
        remote_user: admin
        remote_key: ${{ secrets.DEPLOY_KEY }}
    - name : Install package
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: www.wyvernpserver.tech
        username: admin
        password: haibaconga
        port: 22
        script: >
          cd ebird/server &&
          fuser -k -n tcp 7137 &&
          nohup ./DEPLOY_SERVER.sh &
          
